"""
CATG -> JUnit adapter (Group 9).

Turn CATG''s generated symbolic inputs into a real JUnit suite so the shared
Defects4J pipeline can measure it (compile -> run -> fault detection ->
line/branch coverage).

CATG (concolic testing, Java 8 + CVC4) works by asking the target class to
re-read inputs via `catg.CATG.readString(...)` inside a *driver* main(), so it
produces `inputs` / `catg.generated_inputs` files rather than JUnit classes.
This adapter reads those generated inputs and emits one

    @Test public void test_<bug>_in<k>() { ... assert ... }

per input for the given target method.

Output layout matches what run_experiment.py expects: a directory of .java
files whose `package` matches the Defects4J test source layout
(Defects4J packs it into src/test/java afterwards).

Usage:

  python catg_to_junit.py --project Lang --bug 1 \
      --target-method org.apache.commons.lang3.math.NumberUtils::createNumber \
      --inputs-file ../CATG/Result_Round2/Lang-1_generated_inputs.txt \
      --out-dir ../CATG/TestCode\Lang_1
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

TYPE_BY_PROJECT = {
    # project -> (canonical target class, method to call, param kind)
    "Lang": ("org.apache.commons.lang3.math.NumberUtils", "createNumber", "String"),
}


def _parse_inputs(text: str) -> list[str]:
    """Split the CATG generated-inputs file into one string per input."""
    raw = text.replace("\r\n", "\n").replace("\r", "\n")
    # CATG writes one value per line; blank trailing line is normal.
    vals = [ln.strip() for ln in raw.split("\n") if ln.strip()]
    return vals


def _java_escape(s: str) -> str:
    """Escape a Java string literal body safely."""
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )


def generate(project: str, bug: int, target: str, inputs: list[str]) -> str:
    cls, meth, _kind = TYPE_BY_PROJECT[project]
    pkg = ".".join(cls.split(".")[:-1])
    simple = cls.split(".")[-1]

    lines: list[str] = [f"package {pkg};", "",
                        "import org.junit.Test;",
                        "import static org.junit.Assert.*;",
                        f"import {cls};",
                        ""]
    lines.append(f"public class CATG_{project}_{bug}Test {{")
    lines.append("")
    lines.append("    /** Generated by CATG concolic inputs -> JUnit adapter. */")

    for k, raw in enumerate(inputs, 1):
        literal = '"' + _java_escape(raw) + '"'
        lines.append("")
        lines.append(f"    @Test(timeout = 10000)")
        lines.append(f"    public void test_{project.lower()}{bug}_in{k}() throws Exception {{")
        lines.append(f"        String s = {literal};")
        lines.append(f"        Object r = {simple}.{meth}(s);")
        lines.append("        assertNotNull(\"createNumber(\" + s + \") returned null\", r);")
        lines.append("    }")
        lines.append("")

    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--project", required=True)
    p.add_argument("--bug", type=int, required=True)
    p.add_argument("--target-method", required=True,
                   help="full class::method, e.g. org.apache.commons.lang3.math.NumberUtils::createNumber")
    p.add_argument("--inputs-file", type=Path, required=True)
    p.add_argument("--out-dir", type=Path, required=True)
    args = p.parse_args()

    inputs = _parse_inputs(args.inputs_file.read_text(encoding="utf-8", errors="replace"))
    if not inputs:
        raise SystemExit("no generated inputs found")

    java = generate(args.project, args.bug, args.target_method, inputs)

    out = args.out_dir / f"CATG_{args.project}_{args.bug}Test.java"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(java, encoding="utf-8")
    print(f"[adapter] wrote {out}  ({len(inputs)} @Test from CATG inputs)")


if __name__ == "__main__":
    main()
